package tpdpbofix;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author surya
 */
public class author extends javax.swing.JPanel {

    /**
     * Creates new form author
     */
    dbConnection dbcon = new dbConnection();
    public author() {
        initComponents();
        tab_author.setModel(dbcon.readTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        author = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_author = new javax.swing.JTable();
        add_author = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        update_author = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_nama = new javax.swing.JTextField();
        add_jumlah = new javax.swing.JTextField();
        add_bio = new javax.swing.JTextField();

        author.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        author.setText("DATA AUTHOR");

        tab_author.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jumlah_Buku", "Bio_Singkat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_authorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_author);

        add_author.setText("Add");
        add_author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_authorMouseClicked(evt);
            }
        });
        add_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_authorActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        update_author.setText("Update");

        jLabel1.setText("Nama");

        jLabel2.setText("Jumlah Buku");

        jLabel3.setText("Bio Singkat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(author)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(add_author)
                                        .addGap(123, 123, 123)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(update_author))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(add_bio))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_nama)
                                    .addComponent(add_jumlah)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(author)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(add_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(add_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(add_bio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_author)
                    .addComponent(jButton2)
                    .addComponent(update_author))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_authorActionPerformed

    private void add_authorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_authorMouseClicked
        // TODO add your handling code here:
        if(!add_nama.getText().isEmpty() && !add_jumlah.getText().isEmpty() && !add_bio.getText().isEmpty()){
            String Nama = add_nama.getText();
            String Jumlah_Buku = add_jumlah.getText();
            String Bio_Singkat = add_bio.getText();
            dbcon.Query("insert into author (Nama, Jumlah_Buku, Bio_Singkat) values ('"+Nama+"','"+Jumlah_Buku+"','"+Bio_Singkat+"')");
            tab_author.setModel(dbcon.readTable());
        }
        
    }//GEN-LAST:event_add_authorMouseClicked

    private void tab_authorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_authorMouseClicked
        // TODO add your handling code here:
         int row = tab_author.getSelectedRow();
        String selectedNama = (tab_author.getModel().getValueAt(row, 0).toString());
        String selectedJumlah_Buku = (tab_author.getModel().getValueAt(row, 1).toString());
        String selectedBio_Singkat = (tab_author.getModel().getValueAt(row, 2).toString());

        //System.out.println(selectedID);
        add_nama.setText(selectedNama);
        add_jumlah.setText(selectedJumlah_Buku);
        add_bio.setText(selectedBio_Singkat);
    }//GEN-LAST:event_tab_authorMouseClicked

    public void deleteData() {
        // Get Data
        int row = tab_author.getSelectedRow();
        String selectedNama = (tab_author.getModel().getValueAt(row, 0).toString());
        String selectedjml = (tab_author.getModel().getValueAt(row, 1).toString());
        String selectedbio = (tab_author.getModel().getValueAt(row, 2).toString());
        
        dbcon.Query("delete from author where Nama='"+selectedNama+"' and Jumlah_Buku='"+selectedjml+"'");
        tab_author.setModel(dbcon.readTable());
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    }   
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_author;
    private javax.swing.JTextField add_bio;
    private javax.swing.JTextField add_jumlah;
    private javax.swing.JTextField add_nama;
    private javax.swing.JLabel author;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_author;
    private javax.swing.JButton update_author;
    // End of variables declaration//GEN-END:variables
}
