package tpdpbofix;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author surya
 */
public class buku extends javax.swing.JPanel {

    /**
     * Creates new form author
     */
    dbConnection dbcon = new dbConnection();
    public buku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buku = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_buku = new javax.swing.JTable();
        add_buku = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        add_judul = new javax.swing.JLabel();
        add_authorbuku = new javax.swing.JLabel();
        add_desc = new javax.swing.JLabel();
        input_judul = new javax.swing.JTextField();
        input_author = new javax.swing.JTextField();
        input_desc = new javax.swing.JTextField();
        add_penerbit = new javax.swing.JLabel();
        input_penerbit = new javax.swing.JTextField();

        buku.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buku.setText("DATA BUKU");

        tab_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul", "Author", "Penerbit", "Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_buku);

        add_buku.setText("Add");
        add_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_bukuMouseClicked(evt);
            }
        });
        add_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bukuActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");

        jButton3.setText("Update");

        add_judul.setText("Judul");

        add_authorbuku.setText("Author");

        add_desc.setText("Desc");

        input_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_judulActionPerformed(evt);
            }
        });

        add_penerbit.setText("Penerbit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(buku))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_authorbuku)
                                    .addComponent(add_judul))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_author, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(add_desc)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(add_buku)
                                                .addGap(112, 112, 112)
                                                .addComponent(jButton2)
                                                .addGap(121, 121, 121)
                                                .addComponent(jButton3))
                                            .addComponent(input_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(add_penerbit)
                                        .addGap(18, 18, 18)
                                        .addComponent(input_penerbit)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buku)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_judul)
                    .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_authorbuku)
                    .addComponent(input_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_penerbit)
                    .addComponent(input_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_desc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_buku)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bukuActionPerformed
        // TODO add your handling code here:
//        if (isUpdate == false)
//            insertData();
//        else {
//            updateData();
//            add_buku.setText("Add");
//            TombolDelete.setVisible(false);
//            this.isUpdate = false;
//        }
    }//GEN-LAST:event_add_bukuActionPerformed

    private void input_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_judulActionPerformed

    private void add_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_bukuMouseClicked
        // TODO add your handling code here:
        if(!input_judul.getText().isEmpty() && !input_author.getText().isEmpty() && !input_penerbit.getText().isEmpty() && !input_desc.getText().isEmpty()){
            String Judul = input_judul.getText();
            String authorr = input_author.getText();
            String penerbit = input_penerbit.getText();
            String desc = input_desc.getText();
            dbcon.Query("insert into author (Judul, Author, Penerbit, Desc) values ('"+Judul+"','"+authorr+"','"+penerbit+"','"+desc+"')");
            tab_buku.setModel(dbcon.readTable2());
        }
    }//GEN-LAST:event_add_bukuMouseClicked

    private void tab_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_bukuMouseClicked
        // TODO add your handling code here:
        int row = tab_buku.getSelectedRow();
        String selectedJudul = (tab_buku.getModel().getValueAt(row, 0).toString());
        String selectedAuthor = (tab_buku.getModel().getValueAt(row, 1).toString());
        String selectedPenerbit = (tab_buku.getModel().getValueAt(row, 2).toString());
        String selectedDesc = (tab_buku.getModel().getValueAt(row, 3).toString());

        //System.out.println(selectedID);
        input_judul.setText(selectedJudul);
        input_author.setText(selectedAuthor);
        input_penerbit.setText(selectedPenerbit);
        input_desc.setText(selectedDesc);
    }//GEN-LAST:event_tab_bukuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_authorbuku;
    private javax.swing.JButton add_buku;
    private javax.swing.JLabel add_desc;
    private javax.swing.JLabel add_judul;
    private javax.swing.JLabel add_penerbit;
    private javax.swing.JLabel buku;
    private javax.swing.JTextField input_author;
    private javax.swing.JTextField input_desc;
    private javax.swing.JTextField input_judul;
    private javax.swing.JTextField input_penerbit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_buku;
    // End of variables declaration//GEN-END:variables
}
